"""fixed typo in relationship in  url

Revision ID: 0255b9c8dc8c
Revises: 040d471bdf71
Create Date: 2023-11-20 17:45:11.099114

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0255b9c8dc8c"
down_revision = "040d471bdf71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
