"""added url and user relationship

Revision ID: 040d471bdf71
Revises: cb19dfca774e
Create Date: 2023-11-20 17:41:56.456822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040d471bdf71'
down_revision = 'cb19dfca774e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'urls', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'urls', type_='foreignkey')
    op.drop_column('urls', 'owner_id')
    # ### end Alembic commands ###
