"""renamed url netloc to hostname

Revision ID: 388d699c0bd4
Revises: 968a097da660
Create Date: 2023-11-18 15:25:59.199354

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "388d699c0bd4"
down_revision = "968a097da660"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("urls", sa.Column("hostname", sa.String(), nullable=True))
    op.drop_index("ix_urls_netloc", table_name="urls")
    op.create_index(
        op.f("ix_urls_hostname"), "urls", ["hostname"], unique=False
    )
    op.drop_column("urls", "netloc")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "urls",
        sa.Column("netloc", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_urls_hostname"), table_name="urls")
    op.create_index("ix_urls_netloc", "urls", ["netloc"], unique=False)
    op.drop_column("urls", "hostname")
    # ### end Alembic commands ###
