"""added status code to request

Revision ID: 6516418405ae
Revises: 74e23d388d5c
Create Date: 2023-11-21 23:47:24.541575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6516418405ae'
down_revision = '74e23d388d5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('status_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'status_code')
    # ### end Alembic commands ###
