"""added parameters and method to request table

Revision ID: 74e23d388d5c
Revises: 475b13ed419c
Create Date: 2023-11-21 08:13:53.590529

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "74e23d388d5c"
down_revision = "475b13ed419c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("requests", sa.Column("method", sa.String(), nullable=True))
    op.add_column(
        "requests", sa.Column("parameters", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_requests_method"), "requests", ["method"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_requests_method"), table_name="requests")
    op.drop_column("requests", "parameters")
    op.drop_column("requests", "method")
    # ### end Alembic commands ###
