"""create urls table

Revision ID: 968a097da660
Revises: 2259f20dedb2
Create Date: 2023-11-18 15:17:37.496932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968a097da660'
down_revision = '2259f20dedb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('netloc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_netloc'), 'urls', ['netloc'], unique=False)
    op.add_column('requests', sa.Column('url_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'requests', 'urls', ['url_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'url_id')
    op.drop_index(op.f('ix_urls_netloc'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
