"""Changed field response to json type

Revision ID: c3ed7091ce19
Revises: 67754247997f
Create Date: 2023-01-28 18:26:11.135517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ed7091ce19'
down_revision = '67754247997f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_requests_endpoint', table_name='requests')
    op.drop_index('ix_requests_id', table_name='requests')
    op.drop_index('ix_requests_response', table_name='requests')
    op.drop_table('requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('endpoint', sa.VARCHAR(), nullable=True),
    sa.Column('response', sa.VARCHAR(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requests_response', 'requests', ['response'], unique=False)
    op.create_index('ix_requests_id', 'requests', ['id'], unique=False)
    op.create_index('ix_requests_endpoint', 'requests', ['endpoint'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
