"""added missing url field to request

Revision ID: cb19dfca774e
Revises: 388d699c0bd4
Create Date: 2023-11-18 16:20:31.306135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb19dfca774e'
down_revision = '388d699c0bd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
